# Generated by Django 6.1.1 on 2026-09-15 17:37

import catalog.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_remove_redundant_relation_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='долгота')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('district', models.CharField(max_length=150, verbose_name='район')),
                ('full_address', models.CharField(max_length=300, verbose_name='полный адрес')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_points', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'точка самовывоза',
                'verbose_name_plural': 'точки самовывоза',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.PositiveIntegerField(editable=False, verbose_name='номер в каталоге менеджера')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('minute_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='минутная ставка')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ON_MODERATION', 'На модерации'), ('PUBLISHED', 'Опубликован'), ('REJECTED', 'Отклонён'), ('FROZEN', 'Заморожен'), ('HIDDEN_BY_ADMIN', 'Скрыт администратором')], default='DRAFT', max_length=20, verbose_name='статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='дата первой публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='категория')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.pickuppoint', verbose_name='точка самовывоза')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_number', models.PositiveIntegerField(editable=False, verbose_name='номер экземпляра в товаре')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='инвентарный номер')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Свободен'), ('RESERVED', 'Забронирован'), ('PICKUP_IN_PROGRESS', 'Оформляется выдача'), ('RENTED', 'В аренде'), ('RETURN_INSPECTION', 'Оформляется возврат'), ('MAINTENANCE', 'На обслуживании'), ('DELETED', 'Удалён')], default='AVAILABLE', max_length=24, verbose_name='операционный статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='мягко удалён')),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_instances', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'экземпляр товара',
                'verbose_name_plural': 'экземпляры товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.product_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), catalog.models.validate_product_photo], verbose_name='фотография')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='порядок отображения')),
                ('is_primary', models.BooleanField(default=False, verbose_name='основная фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'фотография товара',
                'verbose_name_plural': 'фотографии товаров',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['manager', 'city'], name='pickup_manager_city_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'id'], name='product_status_id_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manager', 'status', 'id'], name='product_manager_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='product_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('manager', 'catalog_number'), name='product_manager_catalog_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('DRAFT', 'ON_MODERATION', 'PUBLISHED', 'REJECTED', 'FROZEN', 'HIDDEN_BY_ADMIN'))), name='product_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('minute_rate__gt', 0)), name='product_positive_minute_rate'),
        ),
        migrations.AddIndex(
            model_name='productinstance',
            index=models.Index(fields=['product', 'status', 'is_deleted'], name='instance_product_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='productinstance',
            constraint=models.UniqueConstraint(fields=('product', 'instance_number'), name='instance_product_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='productinstance',
            constraint=models.UniqueConstraint(fields=('manager', 'inventory_number'), name='instance_manager_inventory_unique'),
        ),
        migrations.AddConstraint(
            model_name='productinstance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('AVAILABLE', 'RESERVED', 'PICKUP_IN_PROGRESS', 'RENTED', 'RETURN_INSPECTION', 'MAINTENANCE', 'DELETED'))), name='instance_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='productinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_deleted', True), ('status', 'DELETED')), models.Q(models.Q(('status', 'DELETED'), _negated=True), ('is_deleted', False)), _connector='OR'), name='instance_deleted_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='productphoto',
            index=models.Index(fields=['product', 'display_order', 'id'], name='photo_product_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='product_one_primary_photo'),
        ),
    ]
