# Generated by Django 6.1.1 on 2026-09-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Введите номер вручную или запросите генерацию в формате N-M.', max_length=100, verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(help_text='Менеджер экземпляра определяется по владельцу товара.', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.product', verbose_name='товар'),
        ),
    ]
