# Generated by Django 6.1.1 on 2026-09-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productinstance_inventory_number_and_more'),
        ('categories', '0002_remove_redundant_relation_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='числовое значение')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='логическое значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='categories.characteristic', verbose_name='характеристика')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='categories.characteristicoption', verbose_name='вариант')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'значение характеристики товара',
                'verbose_name_plural': 'значения характеристик товаров',
                'indexes': [models.Index(fields=['characteristic', 'option', 'product'], name='product_char_option_idx'), models.Index(fields=['characteristic', 'number_value', 'product'], name='product_char_number_idx'), models.Index(fields=['characteristic', 'boolean_value', 'product'], name='product_char_boolean_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'characteristic'), name='product_one_characteristic_value'), models.CheckConstraint(condition=models.Q(models.Q(('boolean_value__isnull', True), ('number_value__isnull', True), ('option__isnull', False)), models.Q(('boolean_value__isnull', True), ('number_value__isnull', False), ('option__isnull', True)), models.Q(('boolean_value__isnull', False), ('number_value__isnull', True), ('option__isnull', True)), _connector='OR'), name='product_characteristic_one_typed_value')],
            },
        ),
    ]
