# Generated by Django 6.1.1 on 2026-09-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcharacteristicvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.pickuppoint', verbose_name='точка самовывоза'),
        ),
    ]
