# Generated by Django 6.1.1 on 2026-09-20 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_existing_moderation_decisions(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ModerationDecision = apps.get_model("catalog", "ModerationDecision")
    decisions = []
    for product in Product.objects.filter(
        status__in=("PUBLISHED", "FROZEN", "HIDDEN_BY_ADMIN", "REJECTED")
    ).iterator():
        rejected = product.status == "REJECTED"
        decisions.append(
            ModerationDecision(
                product_id=product.pk,
                manager_id=product.manager_id,
                product_name=product.name,
                decision="REJECTED" if rejected else "APPROVED",
                reason=product.rejection_reason if rejected else "",
                is_automatic=not rejected,
            )
        )
    ModerationDecision.objects.bulk_create(decisions)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_pickup_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('auto_approve_new_submissions', models.BooleanField(default=False, help_text='Действует только на заявки, отправленные после включения. Текущая очередь не изменяется.', verbose_name='автоматически одобрять новые заявки')),
            ],
            options={
                'verbose_name': 'настройка модерации',
                'verbose_name_plural': 'настройка модерации',
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='название товара')),
                ('decision', models.CharField(choices=[('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], max_length=16, verbose_name='решение')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='автоматическое решение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата решения')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_moderation_decisions', to=settings.AUTH_USER_MODEL, verbose_name='администратор')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_decisions', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_decisions', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'решение модерации',
                'verbose_name_plural': 'решения модерации',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['manager', 'decision'], name='moderation_mgr_decision_idx')],
            },
        ),
        migrations.RunPython(
            backfill_existing_moderation_decisions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
