# Generated by Django 6.1.1 on 2026-09-28 20:26

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_active_maintenances(apps, schema_editor):
    Maintenance = apps.get_model('catalog', 'Maintenance')
    ProductInstance = apps.get_model('catalog', 'ProductInstance')
    ReturnAct = apps.get_model('applications', 'ReturnAct')

    instances = ProductInstance.objects.filter(
        status='MAINTENANCE',
        is_deleted=False,
    )
    for instance in instances.iterator():
        if Maintenance.objects.filter(
            instance_id=instance.pk,
            completed_at__isnull=True,
        ).exists():
            continue
        source_return = (
            ReturnAct.objects.filter(
                rental__booking__instance_id=instance.pk,
                rental__status='COMPLETED',
                next_instance_status='MAINTENANCE',
            )
            .order_by('-rental__ended_at', '-id')
            .first()
        )
        reason = 'Обслуживание (перенесено при обновлении)'
        if source_return is not None:
            reason = (
                source_return.maintenance_reason.strip()
                or source_return.damage_description.strip()
                or reason
            )
        Maintenance.objects.create(
            instance_id=instance.pk,
            started_by_id=instance.manager_id,
            source_return_act_id=(
                source_return.pk if source_return is not None else None
            ),
            reason=reason,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_returnact_maintenance_reason'),
        ('catalog', '0005_moderationsettings_moderationdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина обслуживания')),
                ('damage_description', models.TextField(blank=True, verbose_name='описание повреждения')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стоимость ремонта')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='catalog.productinstance', verbose_name='экземпляр')),
                ('source_return_act', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='applications.returnact', verbose_name='возврат-источник')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'обслуживание',
                'verbose_name_plural': 'обслуживания',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.maintenance_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), catalog.models.validate_product_photo], verbose_name='фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.maintenance', verbose_name='обслуживание')),
            ],
            options={
                'verbose_name': 'фотография обслуживания',
                'verbose_name_plural': 'фотографии обслуживания',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['instance', 'completed_at', 'started_at'], name='maintenance_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('instance',), name='instance_one_active_maintenance'),
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.CheckConstraint(condition=models.Q(('repair_cost__isnull', True), ('repair_cost__gte', 0), _connector='OR'), name='maintenance_repair_cost_nonnegative'),
        ),
        migrations.RunPython(
            backfill_active_maintenances,
            migrations.RunPython.noop,
        ),
    ]
