# Generated by Django 6.1.1 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="categories.category",
                        verbose_name="родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ("name", "id"),
                "indexes": [
                    models.Index(
                        fields=["parent", "name", "id"],
                        name="cat_parent_name_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LIST", "Список"),
                            ("NUMBER", "Число"),
                            ("BOOLEAN", "Да/нет"),
                        ],
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="обязательная"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="единица измерения",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="порядок отображения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="categories.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика",
                "verbose_name_plural": "характеристики",
                "ordering": ("display_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["category", "display_order", "id"],
                        name="char_category_order_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("type__in", ["LIST", "NUMBER", "BOOLEAN"])),
                        name="char_valid_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("type", "NUMBER"), ~models.Q(("unit", ""))),
                            models.Q(
                                ~models.Q(("type", "NUMBER")),
                                ("unit", ""),
                            ),
                            _connector="OR",
                        ),
                        name="char_unit_matches_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacteristicOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=150, verbose_name="значение")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="порядок отображения",
                    ),
                ),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="categories.characteristic",
                        verbose_name="характеристика",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант списочной характеристики",
                "verbose_name_plural": "варианты списочных характеристик",
                "ordering": ("display_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["characteristic", "display_order", "id"],
                        name="char_option_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("characteristic", "value"),
                        name="char_option_unique_value",
                    )
                ],
            },
        ),
    ]
