# Generated by Django 6.1.1 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="categories.category",
                verbose_name="родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="category",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="categories.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="characteristicoption",
            name="characteristic",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="categories.characteristic",
                verbose_name="характеристика",
            ),
        ),
    ]
