# Generated by Django 6.1.1 on 2026-09-21 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_moderationsettings_moderationdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerQueuePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.CharField(choices=[('EARLIEST', 'Сначала ранние'), ('LATEST', 'Сначала поздние'), ('NEAREST', 'Ближайшие')], default='EARLIEST', max_length=16, verbose_name='сортировка')),
                ('hide_unavailable', models.BooleanField(default=False, verbose_name='скрывать товары без свободных экземпляров')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_queue_preference', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'настройка очереди заявок',
                'verbose_name_plural': 'настройки очереди заявок',
            },
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_deadline_at', models.DateTimeField(verbose_name='крайний срок получения')),
                ('planned_return_at', models.DateTimeField(verbose_name='плановый срок возврата')),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает решения'), ('CANCELLED', 'Отменена'), ('EXPIRED', 'Срок получения истёк')], default='WAITING', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='причина отмены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='catalog.product', verbose_name='товар')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to=settings.AUTH_USER_MODEL, verbose_name='арендатор')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATED', 'Заявка создана'), ('CANCELLED', 'Заявка отменена'), ('EXPIRED', 'Срок получения истёк')], max_length=16, verbose_name='событие')),
                ('actor', models.CharField(choices=[('RENTER', 'Арендатор'), ('MANAGER', 'Менеджер'), ('SYSTEM', 'Система')], max_length=16, verbose_name='инициатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата события')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.rentalapplication', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'событие заявки',
                'verbose_name_plural': 'события заявок',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['renter', 'product', 'status'], name='application_renter_product_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['product', 'status', 'pickup_deadline_at'], name='application_product_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalapplication',
            constraint=models.CheckConstraint(condition=models.Q(('planned_return_at__gte', models.F('pickup_deadline_at'))), name='application_return_not_before_pickup'),
        ),
        migrations.AddConstraint(
            model_name='rentalapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('WAITING', 'CANCELLED', 'EXPIRED'))), name='application_valid_status'),
        ),
    ]
