# Generated by Django 6.1.1 on 2026-09-24 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('catalog', '0005_moderationsettings_moderationdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATED', 'Бронь создана'), ('ARRIVAL_CONFIRMED', 'Прибытие подтверждено'), ('CANCELLED', 'Бронь отменена'), ('EXPIRED', 'Бронь истекла автоматически')], max_length=24, verbose_name='событие')),
                ('actor', models.CharField(choices=[('RENTER', 'Арендатор'), ('MANAGER', 'Менеджер'), ('SYSTEM', 'Система')], max_length=16, verbose_name='инициатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата события')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'событие брони',
                'verbose_name_plural': 'события брони',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ждёт арендатора'), ('ARRIVED', 'Арендатор прибыл'), ('CANCELLED', 'Отменена'), ('EXPIRED', 'Истекла автоматически')], default='ACTIVE', max_length=16, verbose_name='статус')),
                ('minute_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='зафиксированная ставка')),
                ('starting_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='зафиксированная стартовая стоимость')),
                ('arrival_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='прибытие подтверждено')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='причина отмены')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
            },
        ),
        migrations.RemoveConstraint(
            model_name='rentalapplication',
            name='application_valid_status',
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Заявка создана'), ('BOOKED', 'Создана бронь'), ('CANCELLED', 'Заявка отменена'), ('EXPIRED', 'Срок получения истёк')], max_length=16, verbose_name='событие'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидает решения'), ('BOOKED', 'Преобразована в бронь'), ('CANCELLED', 'Отменена'), ('EXPIRED', 'Срок получения истёк')], default='WAITING', max_length=16, verbose_name='статус'),
        ),
        migrations.AddConstraint(
            model_name='rentalapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('WAITING', 'BOOKED', 'CANCELLED', 'EXPIRED'))), name='application_valid_status'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='applications.rentalapplication', verbose_name='заявка'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.productinstance', verbose_name='экземпляр'),
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.rentalbooking', verbose_name='бронь'),
        ),
        migrations.AddIndex(
            model_name='rentalbooking',
            index=models.Index(fields=['status', 'application'], name='booking_status_application_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalbooking',
            index=models.Index(fields=['status', 'created_at'], name='booking_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalbooking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'ARRIVED', 'CANCELLED', 'EXPIRED'))), name='booking_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='rentalbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('ACTIVE', 'ARRIVED'))), fields=('instance',), name='booking_one_current_per_instance'),
        ),
    ]
