# Generated by Django 6.1.1 on 2026-09-26 19:02

import applications.models
import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_bookingevent_rentalbooking_and_more'),
        ('catalog', '0005_moderationsettings_moderationdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_comment', models.TextField(blank=True, verbose_name='комментарий арендатора')),
                ('manager_comment', models.TextField(blank=True, verbose_name='комментарий менеджера')),
                ('renter_completed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_completed_at', models.DateTimeField(blank=True, null=True)),
                ('renter_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('renter_revision', models.PositiveIntegerField(default=0)),
                ('manager_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'фотоакт выдачи',
                'verbose_name_plural': 'фотоакты выдачи',
            },
        ),
        migrations.CreateModel(
            name='HandoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('RENTER', 'Арендатор'), ('MANAGER', 'Менеджер')], max_length=16)),
                ('image', models.ImageField(upload_to=applications.models.handover_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), catalog.models.validate_product_photo], verbose_name='фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'фотография выдачи',
                'verbose_name_plural': 'фотографии выдачи',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('OVERDUE', 'Просрочка'), ('COMPLETED', 'Завершена в тестовом режиме')], default='ACTIVE', max_length=16)),
                ('minute_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starting_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planned_return_at', models.DateTimeField()),
                ('rental_started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'аренда',
                'verbose_name_plural': 'аренды',
            },
        ),
        migrations.RemoveConstraint(
            model_name='rentalbooking',
            name='booking_valid_status',
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Бронь создана'), ('ARRIVAL_CONFIRMED', 'Прибытие подтверждено'), ('MATERIALS_COMPLETED', 'Фиксация завершена'), ('CHANGES_REQUESTED', 'Запрошено изменение фиксации'), ('HANDOVER_CONFIRMED', 'Фотоакт подтверждён'), ('RENTAL_STARTED', 'Аренда началась'), ('CANCELLED', 'Бронь отменена'), ('EXPIRED', 'Бронь истекла автоматически')], max_length=24, verbose_name='событие'),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ждёт арендатора'), ('ARRIVED', 'Арендатор прибыл'), ('RENTED', 'Аренда началась'), ('CANCELLED', 'Отменена'), ('EXPIRED', 'Истекла автоматически')], default='ACTIVE', max_length=16, verbose_name='статус'),
        ),
        migrations.AddConstraint(
            model_name='rentalbooking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'ARRIVED', 'RENTED', 'CANCELLED', 'EXPIRED'))), name='booking_valid_status'),
        ),
        migrations.AddField(
            model_name='handoveract',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='applications.rentalbooking', verbose_name='бронь'),
        ),
        migrations.AddField(
            model_name='handoverphoto',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_photos', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='handoverphoto',
            name='handover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='applications.handoveract', verbose_name='фотоакт'),
        ),
        migrations.AddField(
            model_name='rental',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rental', to='applications.rentalbooking', verbose_name='бронь'),
        ),
        migrations.AddIndex(
            model_name='handoverphoto',
            index=models.Index(fields=['handover', 'author_role', 'id'], name='handover_photo_party_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status', 'planned_return_at'], name='rental_status_return_idx'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'OVERDUE', 'COMPLETED'))), name='rental_valid_status'),
        ),
    ]
