# Generated by Django 6.1.1 on 2026-09-27 12:42

import applications.models
import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_handoveract_handoverphoto_rental_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('RETURN_RECEIVED', 'Возврат принят'), ('MATERIALS_COMPLETED', 'Фиксация завершена'), ('CHANGES_REQUESTED', 'Запрошено изменение фиксации'), ('SURCHARGE_WAIVED', 'Коэффициент просрочки отменён'), ('DAMAGE_UPDATED', 'Штраф за повреждение изменён'), ('DAMAGE_ACCEPTED', 'Штраф принят'), ('DAMAGE_REJECTED', 'Штраф отклонён'), ('RETURN_CONFIRMED', 'Фотоакт возврата подтверждён'), ('RETURN_COMPLETED', 'Возврат завершён')], max_length=32, verbose_name='событие')),
                ('actor', models.CharField(choices=[('RENTER', 'Арендатор'), ('MANAGER', 'Менеджер'), ('SYSTEM', 'Система')], max_length=16, verbose_name='инициатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата события')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'событие аренды',
                'verbose_name_plural': 'события аренды',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReturnAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_comment', models.TextField(blank=True, verbose_name='комментарий арендатора')),
                ('manager_comment', models.TextField(blank=True, verbose_name='комментарий менеджера')),
                ('renter_completed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_completed_at', models.DateTimeField(blank=True, null=True)),
                ('renter_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('renter_revision', models.PositiveIntegerField(default=0)),
                ('manager_revision', models.PositiveIntegerField(default=0)),
                ('late_surcharge_waived', models.BooleanField(default=False)),
                ('late_surcharge_waiver_reason', models.TextField(blank=True)),
                ('late_surcharge_waived_at', models.DateTimeField(blank=True, null=True)),
                ('damage_enabled', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_decision', models.CharField(choices=[('NONE', 'Штраф не указан'), ('PENDING', 'Ожидает решения арендатора'), ('ACCEPTED', 'Согласовано'), ('REJECTED', 'Отклонено')], default='NONE', max_length=16)),
                ('next_instance_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Доступен'), ('MAINTENANCE', 'На обслуживании')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'фотоакт возврата',
                'verbose_name_plural': 'фотоакты возврата',
            },
        ),
        migrations.CreateModel(
            name='ReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('RENTER', 'Арендатор'), ('MANAGER', 'Менеджер')], max_length=16)),
                ('image', models.ImageField(upload_to=applications.models.return_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), catalog.models.validate_product_photo], verbose_name='фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'фотография возврата',
                'verbose_name_plural': 'фотографии возврата',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='rental',
            name='rental_valid_status',
        ),
        migrations.AddField(
            model_name='rental',
            name='return_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('OVERDUE', 'Просрочка'), ('RETURN_INSPECTION', 'Оформляется возврат'), ('COMPLETED', 'Завершена')], default='ACTIVE', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'OVERDUE', 'RETURN_INSPECTION', 'COMPLETED'))), name='rental_valid_status'),
        ),
        migrations.AddField(
            model_name='rentalevent',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.rental', verbose_name='аренда'),
        ),
        migrations.AddField(
            model_name='returnact',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_act', to='applications.rental', verbose_name='аренда'),
        ),
        migrations.AddField(
            model_name='returnphoto',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_photos', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='returnphoto',
            name='return_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='applications.returnact', verbose_name='фотоакт'),
        ),
        migrations.AddConstraint(
            model_name='returnact',
            constraint=models.CheckConstraint(condition=models.Q(('damage_amount__gte', 0)), name='return_damage_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='returnphoto',
            index=models.Index(fields=['return_act', 'author_role', 'id'], name='return_photo_party_idx'),
        ),
    ]
