# Generated by Django 6.1.1 on 2026-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rentalevent_returnact_returnphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnact',
            name='maintenance_reason',
            field=models.TextField(blank=True),
        ),
    ]
