"""Versioned API routes for rental applications."""

from applications.views import (
    HandoverCompleteView,
    HandoverConfirmView,
    HandoverMaterialsView,
    HandoverPhotoListView,
    HandoverPhotoView,
    HandoverRequestChangesView,
    ManagerApplicationBookView,
    ManagerApplicationCancelView,
    ManagerApplicationDetailView,
    ManagerApplicationListView,
    ManagerBookingArrivalView,
    ManagerBookingCancelView,
    ManagerBookingDetailView,
    ManagerBookingListView,
    ManagerQueuePreferenceView,
    ManagerReturnReceiveView,
    ProductApplicationCreateView,
    RentalDetailView,
    RentalListView,
    RenterActivityView,
    RenterApplicationCancelView,
    RenterApplicationDetailView,
    RenterApplicationListView,
    RenterBookingCancelView,
    RenterBookingDetailView,
    RenterBookingListView,
    ReturnCompleteView,
    ReturnConfirmView,
    ReturnDamageDecisionView,
    ReturnFinancialsView,
    ReturnFinishView,
    ReturnMaterialsView,
    ReturnPhotoListView,
    ReturnPhotoView,
    ReturnRequestChangesView,
)
from django.urls import path

app_name = "applications"

urlpatterns = [
    path("activity/", RenterActivityView.as_view(), name="renter-activity"),
    path(
        "products/<int:pk>/applications/",
        ProductApplicationCreateView.as_view(),
        name="product-application-create",
    ),
    path("applications/", RenterApplicationListView.as_view(), name="renter-list"),
    path(
        "applications/<int:pk>/",
        RenterApplicationDetailView.as_view(),
        name="renter-detail",
    ),
    path(
        "applications/<int:pk>/cancel/",
        RenterApplicationCancelView.as_view(),
        name="renter-cancel",
    ),
    path(
        "manager/applications/",
        ManagerApplicationListView.as_view(),
        name="manager-list",
    ),
    path(
        "manager/applications/<int:pk>/",
        ManagerApplicationDetailView.as_view(),
        name="manager-detail",
    ),
    path(
        "manager/applications/<int:pk>/cancel/",
        ManagerApplicationCancelView.as_view(),
        name="manager-cancel",
    ),
    path(
        "manager/applications/<int:pk>/book/",
        ManagerApplicationBookView.as_view(),
        name="manager-book",
    ),
    path(
        "manager/application-preferences/",
        ManagerQueuePreferenceView.as_view(),
        name="manager-preferences",
    ),
    path("bookings/", RenterBookingListView.as_view(), name="renter-booking-list"),
    path(
        "bookings/<int:pk>/",
        RenterBookingDetailView.as_view(),
        name="renter-booking-detail",
    ),
    path(
        "bookings/<int:pk>/cancel/",
        RenterBookingCancelView.as_view(),
        name="renter-booking-cancel",
    ),
    path(
        "manager/bookings/",
        ManagerBookingListView.as_view(),
        name="manager-booking-list",
    ),
    path(
        "manager/bookings/<int:pk>/",
        ManagerBookingDetailView.as_view(),
        name="manager-booking-detail",
    ),
    path(
        "manager/bookings/<int:pk>/cancel/",
        ManagerBookingCancelView.as_view(),
        name="manager-booking-cancel",
    ),
    path(
        "manager/bookings/<int:pk>/arrival/",
        ManagerBookingArrivalView.as_view(),
        name="manager-booking-arrival",
    ),
    path(
        "bookings/<int:pk>/handover/photos/",
        HandoverPhotoListView.as_view(),
        name="handover-photo-list",
    ),
    path(
        "bookings/<int:pk>/handover/photos/<int:photo_id>/",
        HandoverPhotoView.as_view(),
        name="handover-photo-delete",
    ),
    path(
        "handover-photos/<int:photo_id>/",
        HandoverPhotoView.as_view(),
        name="handover-photo-file",
    ),
    path(
        "bookings/<int:pk>/handover/materials/",
        HandoverMaterialsView.as_view(),
        name="handover-materials",
    ),
    path(
        "bookings/<int:pk>/handover/complete/",
        HandoverCompleteView.as_view(),
        name="handover-complete",
    ),
    path(
        "bookings/<int:pk>/handover/confirm/",
        HandoverConfirmView.as_view(),
        name="handover-confirm",
    ),
    path(
        "bookings/<int:pk>/handover/request-changes/",
        HandoverRequestChangesView.as_view(),
        name="handover-request-changes",
    ),
    path("rentals/", RentalListView.as_view(), name="rental-list"),
    path("rentals/<int:pk>/", RentalDetailView.as_view(), name="rental-detail"),
    path(
        "manager/rentals/<int:pk>/return/receive/",
        ManagerReturnReceiveView.as_view(),
        name="manager-return-receive",
    ),
    path(
        "rentals/<int:pk>/return/photos/",
        ReturnPhotoListView.as_view(),
        name="return-photo-list",
    ),
    path(
        "rentals/<int:pk>/return/photos/<int:photo_id>/",
        ReturnPhotoView.as_view(),
        name="return-photo-delete",
    ),
    path(
        "return-photos/<int:photo_id>/",
        ReturnPhotoView.as_view(),
        name="return-photo-file",
    ),
    path(
        "rentals/<int:pk>/return/materials/",
        ReturnMaterialsView.as_view(),
        name="return-materials",
    ),
    path(
        "rentals/<int:pk>/return/financials/",
        ReturnFinancialsView.as_view(),
        name="return-financials",
    ),
    path(
        "rentals/<int:pk>/return/complete/",
        ReturnCompleteView.as_view(),
        name="return-complete",
    ),
    path(
        "rentals/<int:pk>/return/request-changes/",
        ReturnRequestChangesView.as_view(),
        name="return-request-changes",
    ),
    path(
        "rentals/<int:pk>/return/damage-decision/",
        ReturnDamageDecisionView.as_view(),
        name="return-damage-decision",
    ),
    path(
        "rentals/<int:pk>/return/confirm/",
        ReturnConfirmView.as_view(),
        name="return-confirm",
    ),
    path(
        "rentals/<int:pk>/return/finish/",
        ReturnFinishView.as_view(),
        name="return-finish",
    ),
]
