# Generated by Django 6.1.1 on 2026-09-12 18:26

import django.db.models.functions.text
import django.utils.timezone
import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='аватар')),
                ('role', models.CharField(choices=[('RENTER', 'Арендатор'), ('MANAGER', 'Менеджер')], max_length=16, verbose_name='роль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='статус персонала')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['RENTER', 'MANAGER'])), name='users_user_valid_role'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_ci_unique')],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
