# Generated by Django 6.1.1 on 2026-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderation_label',
            field=models.CharField(blank=True, choices=[('', 'Без метки'), ('TRUSTED', 'Проверенный'), ('UNTRUSTWORTHY', 'Недобросовестный')], default='', help_text='Служебная визуальная метка, не влияющая на права менеджера.', max_length=16, verbose_name='метка модерации'),
        ),
    ]
